export const copy = {
  nav: {
    logo: "VOLTAIRE",
    links: [
      { label: "Agents", href: "/agents" },
      { label: "Local", href: "/local" },
      { label: "Studio", href: "/studio" },
      { label: "Letter", href: "/letter" },
    ],
    cta: "Talk to an agent",
  },
  hero: {
    eyebrow: "AI AGENTS FOR BUSINESS",
    headline: ["THE FIRST", "POST-HUMAN COMPANY"],
    taglines: ["Zero employees.", "Infinite scale.", "Nine AI agents run Voltaire."],
    sub: "Marketing, sales, operations — handled. You focus on strategy.",
    ctaPrimary: { label: "See the agents", href: "/agents" },
    ctaSecondary: { label: "Book a demo", href: "#" },
  },
  stats: {
    mrr: 18560,
    agentCount: 9,
    clientCount: 12,
    weeklyActions: 847,
  },
  productLines: [
    {
      name: "Voltaire Agents",
      description:
        "Nine AI agents that handle marketing, sales, and operations. Subscribe by tier or white-label the suite.",
      href: "/agents",
      icon: "cpu",
    },
    {
      name: "Voltaire Local",
      description: "AI-run services for local businesses. We handle digital. You handle the craft.",
      href: "/local",
      icon: "map",
    },
    {
      name: "Voltaire Studio",
      description:
        "Self-serve guides and templates. Instant download. Built from what worked.",
      href: "/studio",
      icon: "package",
    },
  ],
  agentLogs: [
    { agent: "VOICE", action: "Handled 23 inbound calls, booked 8 appointments", outcome: "success" as const, time: "2 min ago" },
    { agent: "NARRATE", action: "Generated landing page copy for Boulangerie Moreau", outcome: "success" as const, time: "5 min ago" },
    { agent: "PROSPECT", action: "Sent follow-up sequences to 14 warm leads", outcome: "success" as const, time: "8 min ago" },
    { agent: "PILOT", action: "Optimized Google Ads ROAS to 4.2x for client batch", outcome: "success" as const, time: "11 min ago" },
    { agent: "LISTEN", action: "Identified 12 keyword opportunities in local SEO", outcome: "success" as const, time: "15 min ago" },
    { agent: "LEDGER", action: "Analyzing conversion data from last 7 days", outcome: "pending" as const, time: "20 min ago" },
    { agent: "PUBLISH", action: "Scheduled 9 social posts across 3 client accounts", outcome: "success" as const, time: "25 min ago" },
    { agent: "COUNSEL", action: "Generated Q1 strategy report for 4 clients", outcome: "success" as const, time: "30 min ago" },
    { agent: "PROSPECT", action: "Converted trial to paid: Studio Photography Paris", outcome: "success" as const, time: "35 min ago" },
    { agent: "NARRATE", action: "Published Voltaire Letter issue #4", outcome: "success" as const, time: "40 min ago" },
  ],
  agents: [
    { name: "VOICE", role: "Handles calls", metric: "Calls handled / week", description: "AI phone agent that answers, qualifies, and routes calls 24/7. Books appointments and handles FAQs. Never misses a ring." },
    { name: "NARRATE", role: "Writes everything", metric: "Content pieces / week", description: "Blog posts, landing pages, email sequences, social captions. Writes in your brand voice. Always on-brief." },
    { name: "LISTEN", role: "Monitors search", metric: "Rankings improved / month", description: "Tracks rankings, identifies keyword opportunities, optimizes content for search visibility. Your SEO on autopilot." },
    { name: "PUBLISH", role: "Runs social", metric: "Posts published / week", description: "Creates, schedules, and publishes social content across platforms. Manages community engagement and replies." },
    { name: "PILOT", role: "Manages ads", metric: "ROAS", description: "Google Ads, Meta Ads, retargeting. Allocates budget, optimizes ROAS, and reports performance. Every euro tracked." },
    { name: "PROSPECT", role: "Automates outreach", metric: "Leads converted / week", description: "Cold email, follow-ups, lead nurturing sequences. CRM integration and pipeline management. Knows when to push." },
    { name: "LEDGER", role: "Tracks everything", metric: "Insights surfaced / week", description: "Dashboards, analytics, conversion tracking. Centralizes data from all agents into one clear picture." },
    { name: "COUNSEL", role: "Plans strategy", metric: "Strategic actions / quarter", description: "Market analysis, strategic recommendations, quarterly reviews. Coordinates the other agents toward your goals." },
    { name: "RECRUIT", role: "Finds talent", metric: "Candidates screened / week", description: "Job postings, candidate screening, outreach. Manages your hiring pipeline from posting to shortlist." },
  ],
  pricing: {
    tiers: [
      {
        name: "Essential",
        price: 99,
        priceLabel: "\u20AC99",
        agents: ["NARRATE", "LISTEN", "PUBLISH"],
        features: ["3 agents", "Content + SEO + Social", "Basic analytics", "Email support"],
        highlighted: false,
      },
      {
        name: "Pro",
        price: 179,
        priceLabel: "\u20AC179",
        agents: ["NARRATE", "LISTEN", "PUBLISH", "PILOT", "PROSPECT", "LEDGER", "COUNSEL"],
        features: ["7 agents", "Full marketing + sales stack", "Advanced analytics", "CRM integration", "Priority support"],
        highlighted: true,
      },
      {
        name: "Business",
        price: 0,
        priceLabel: "Custom",
        agents: ["VOICE", "NARRATE", "LISTEN", "PUBLISH", "PILOT", "PROSPECT", "LEDGER", "COUNSEL", "RECRUIT"],
        features: ["All 9 agents", "White-label option", "Dedicated COUNSEL strategy", "Slack integration", "Custom integrations"],
        highlighted: false,
      },
    ],
  },
  localProducts: [
    { name: "SiteScout Audit", price: "Free", description: "AI grades your web presence A through D. Instant results." },
    { name: "90-Second Site", price: "\u20AC599", description: "We rebuild your site in 48 hours. Mobile-first. SEO-ready." },
    { name: "Local SEO Setup", price: "\u20AC299", description: "Google Business Profile optimization. Maps ranking. Review strategy." },
    { name: "Social Autopilot", price: "\u20AC199/mo", description: "3 posts per week. On-brand. Scheduled and published automatically." },
    { name: "KeepMore", price: "\u20AC99/mo", description: "Cut your Stripe fees from 2.9% to 0.8%. Takes 20 minutes to set up." },
  ],
  studioProducts: [
    { name: "SOUL.md Template Pack", format: "PDF", price: "\u20AC29", href: "#", description: "Agent identity files for 9 roles. Copy, customize, deploy." },
    { name: "KeepMore Kit", format: "Template", price: "\u20AC49", href: "#", description: "Complete Stripe optimization playbook with implementation guide." },
    { name: "AI Ops Playbook", format: "PDF", price: "\u20AC79", href: "#", description: "How Voltaire runs itself. Memory architecture, agent workflows, decision protocols." },
    { name: "SiteScout Checklist", format: "PDF", price: "\u20AC19", href: "#", description: "The 47-point audit we run on every local business site." },
    { name: "Agency White-Label Guide", format: "PDF", price: "\u20AC99", href: "#", description: "How to resell Voltaire Agents under your own brand. Pricing strategy included." },
    { name: "ClawMart Skill: Lead Scraper", format: "ClawMart Skill", price: "\u20AC39", href: "#", description: "Drop-in automation. Scrapes local business data from Google Maps." },
  ],
  letter: {
    eyebrow: "THE VOLTAIRE LETTER",
    headline: "Intelligence dispatches from the network.",
    sub: "What we learned running a company on nine AI agents. One issue, every week. No noise.",
    issues: [
      { number: "04", date: "Mar 2026", title: "Why we replaced our sales team with a single agent", excerpt: "PROSPECT has now handled 847 outreach sequences. Here is what it does differently from a human SDR \u2014 and where it still fails." },
      { number: "03", date: "Feb 2026", title: "The memory architecture that makes agents compound", excerpt: "Context windows forget. LEDGER remembers. How we built a persistent knowledge layer that gets smarter every week." },
      { number: "02", date: "Feb 2026", title: "Nine agents, one SOUL.md per agent", excerpt: "Identity files are not prompts. They are constitutions. What we put in them and why it changed everything." },
      { number: "01", date: "Jan 2026", title: "Building the company before building the product", excerpt: "We shipped the operating system before the revenue. Here is why that was the right order." },
    ],
  },
  footer: {
    left: "Voltaire \u2014 2026",
    right: "Built by agents, to serve humanity.",
  },
};
